- src/components/RatingsAndReviews/RatingAndReviews.jsx
Create directory and parent component for RatingsAndReviews
> create RatingsAndReviews component

- src/components/App.jsx
- src/components/RatingsAndReviews/RatingsAndReviews.jsx
correct prop being passed into RR component, add test console.log
> correct prop being passed into RR component

- src/components/RatingsAndReviews/RatingBreakdown.jsx
- src/components/RatingsAndReviews/RatingsAndReviews.jsx
- src/components/RatingsAndReviews/ReviewView.jsx
> create file structure for Ratings & Reviews

- src/components/App.jsx
- src/components/RatingsAndReviews/RatingsAndReviews.jsx
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/ReviewsView.jsx
pass object with HTTP requests to RR component and requests for reviews data
> RR http requests add

- dist/style.css
- src/components/relatedItems/RelatedItems.jsx
- src/components/relatedItems/RelatedProductCard.jsx
styles.css - added a style
components/relatedItems/ - added next pic / prev pic buttons
> added next photo / prev photo buttons, removed a testing console.log, 

- .gitignore
- dist/style.css
- jest.config.js
- package-lock.json
- package.json
- src/components/bridge.js
- src/components/relatedItems/RelatedItems.jsx
- src/components/relatedItems/RelatedProductCard.jsx
- src/components/relatedItems/RelatedProducts.jsx
- src/components/relatedItems/styles.css
- src/tests/RelatedProductCard.test.jsx
- webpack.config.js
package.json - installed additional dependency for jest testing and webpack
bridge - made compliant with eslint, corrected erroneous code. 
RelatedProductCard.jsx and RelatedProductCard.test.js - completed implimenting tests for RelatedProductCard
webpack.config.js - made compliant with eslint, set up to import styles into react components
styles.css - moved relatedItems styles into relatedItems/styles.css
> installed dep for jest, made files compliant with eslint, made tests for RelatedProductCard

- src/components/relatedItems/RelatedProducts.jsx
- src/components/relatedItems/styles.css
components/relatedItems/ - completed list behavior for RelatedProducts component
> finished list behavior for relatedProducs

- .eslintrc.js
- babel.config.js
- package.json
- src/components/productDetails/Overview.jsx
- src/components/productDetails/ProductInformation.jsx
- src/tests/ProductInformation.test.jsx
Added Linter, fixed consequent errors, added propTypes, created testing File for ProductInformation, edited eslintrc.js to solve not recognizing jest error
> adds, fix, etc.

- src/components/App.jsx
- src/components/bridge.js
- src/components/relatedItems/RelatedProductCard.jsx
- src/components/relatedItems/RelatedProducts.jsx
- webpack.config.js
App.jsx & RelatedProducts.jsx - removed the .jsx extensions from the imports
bridge.js - fixed the error and cleaned up in compliance of eslint
webpack.config & .env - set up new environmental variable
RelatedProductCard - started using new environmental variable
> removed .jsx from App and RelatedProducts imports, cleaned up bridge,

- dist/index.html
- src/components/RatingsAndReviews/RatingsAndReviews.css
- src/components/RatingsAndReviews/RatingsAndReviews.jsx
- src/components/RatingsAndReviews/RatingsBreakdown.css
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/ReviewsView.css
- src/components/RatingsAndReviews/ReviewsView.jsx
- src/tests/RatingsBreakdown.test.jsx
Move shared CSS file into widget directory: RatingsBreakdown.css
Create CSS files: RatingsAndReviews.css, ReviewsViews.css
Create test for RatingsBreakdown
Progress on ReviewsView component
> ReviewsView Progress

- src/components/RatingsAndReviews/RatingsAndReviews.jsx
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/ReviewsView.jsx
Added filters to stars
Reimplemented reviews list to grab all data
> Rr filters and styles

- src/components/App.jsx
- src/components/relatedItems/ComparisonModal.jsx
- src/components/relatedItems/ComparisonModalColumn.jsx
- src/components/relatedItems/styles.css
App.js - added ...Loading if no productId to prevent console errors
comparisonModal - set it up so when a new item is selected the currently viewed item should be first. Still need to test
> cleaned up comparisonModal, added ...Loading to App.js if no productId

- src/components/App.jsx
- src/components/RatingsAndReviews/AddReviewModal.css
- src/components/RatingsAndReviews/AddReviewModal.jsx
- src/components/RatingsAndReviews/RatingsAndReviews.css
- src/components/RatingsAndReviews/RatingsAndReviews.jsx
- src/components/RatingsAndReviews/RatingsBreakdown.css
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/ReviewsView.css
- src/components/RatingsAndReviews/ReviewsView.jsx
- src/components/RatingsAndReviews/StarRating.css
- src/components/RatingsAndReviews/StarRating.jsx
- src/components/bridge.js
Add star filter tracker and remove all filters functionality
Add PUT requests for marking reviews helpful or reporting reports. Also fixed axios PUT requests.
Build out characteristic rating bars in RatingsBreakdown component
Implement star rating render for each review tile
Begin work on AddReview modal
ESlint fixes in bridge.js.
> Rr breakdown and view

- src/components/relatedItems/AddItemToOutfit.jsx
- src/components/relatedItems/RelatedItems.jsx
- src/components/relatedItems/RelatedProducts.jsx
- src/components/relatedItems/YourOutfit.jsx
- src/components/relatedItems/styles.css
> Your Outfit

- dist/QuestionsAnswers.css
- src/components/App.jsx
- src/components/QuestionsAnswers/AnswerModal.jsx
- src/components/QuestionsAnswers/QuestionAnswerEntry.jsx
- src/components/QuestionsAnswers/QuestionModal.jsx
- src/components/QuestionsAnswers/QuestionsAnswers.jsx
- src/tests/QuestionsAnswers.test.jsx
finished form validation for both question and answer modal
> Form validation

- src/components/App.jsx
- src/components/relatedItems/AddItemToOutfit.jsx
- src/components/relatedItems/ComparisonModal.jsx
- src/components/relatedItems/ComparisonModalColumn.jsx
- src/components/relatedItems/ComparisonModalRow.jsx
- src/components/relatedItems/GradientEffect.jsx
- src/components/relatedItems/RelatedItems.jsx
- src/components/relatedItems/RelatedProductCard.jsx
- src/components/relatedItems/YourOutfit.jsx
- src/components/relatedItems/styles.css
all work on relatedItems/ - mostly modal and product card styling
> Related items

- src/components/relatedItems/ActionButton.jsx
- src/components/relatedItems/AddItemToOutfit.jsx
- src/components/relatedItems/ComparisonModalRow.jsx
- src/components/relatedItems/RelatedProductCard.jsx
- src/components/relatedItems/RelatedProducts.jsx
- src/components/relatedItems/YourOutfit.jsx
- src/components/relatedItems/styles.css
Added action buttons, completed callback for related outfits button, some styling fixes along the way.
> progress on action buttons, just need RelatedProducts callback and icons

- src/components/App.jsx
- src/components/RatingsAndReviews/AddReviewModal.css
- src/components/RatingsAndReviews/AddReviewModal.jsx
- src/components/RatingsAndReviews/RatingsAndReviews.css
- src/components/RatingsAndReviews/RatingsBreakdown.css
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/ReviewsView.css
- src/components/RatingsAndReviews/ReviewsView.jsx
- src/components/RatingsAndReviews/StarRating.css
- src/components/RatingsAndReviews/StarRating.jsx
- src/components/bridge.js
Implement review modal and form, fix axios POST
Implement image modal for pictures in reviews
> Reviewmodal

- src/components/RatingsAndReviews/AddReviewModal.jsx
- src/components/RatingsAndReviews/RatingsBreakdown.jsx
- src/components/RatingsAndReviews/StarRating.jsx
- src/tests/AddReviewModal.test.jsx
- src/tests/RatingsBreakdown.test.jsx
- src/tests/StarRating.test.jsx
fix broken RatingsBreakdown tests,
add more test files
> jest testing

- src/components/productDetails/ProductInformation.jsx
- src/components/productDetails/StyleSelector.jsx
- src/tests/ProductInformation.test.jsx
- src/tests/StyleSelector.test.jsx
> Product detail
